on: 
  workflow_dispatch:
    inputs:
      path:
        description: Directory to scan
        default: '.'

jobs:
  xygeni-scan:
    runs-on: ubuntu-latest
    name: xygeni-github-action
    steps:
      # Checkout the repository sources (GITHUB_WORKSPACE)
      - name: Checkout
        # You may instead pin to an action SHA
        uses: actions/checkout@v6.0.1

      - name: Show files
        run: |
          echo "Directory: ${{ inputs.path }}"
          ls -la "${{ inputs.path }}"
          find "${{ inputs.path }}" -name "*.py" 

      - name: Xygeni-Scanner
        uses: xygeni/xygeni-action@v5.38.0
        id: Xygeni-Scanner
        with:
          token: ${{ secrets.XYGENI_TOKEN }}
          command: sast -n checkov -d ${{ inputs.path }}
        env:
          _XYGENI_APPLY_POLICIES_: 'never!'
